[package]
name = "nucleo_test"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
cortex-m = "0.7"
cortex-m-rt = "0.7"
embedded-hal = "1.0.0"
panic-halt = "1.0"
stm32f4xx-hal = { version = "0.22", features = ["stm32f446"] }

[profile.release]
opt-level = "z"
lto = true
